# Generated by Django 3.1.2 on 2020-11-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201105_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bandcamp',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='beatport',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='soundcloud',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
