# Generated by Django 3.1.2 on 2020-11-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201101_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
